[package]
name = "fluimte"
version = "0.0.1"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
notify = "6.1.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }


